returnString = '';
returnString += '<p>NepaliFunctions.ConvertToDateObject("2000-01-01", "YYYY-MM-DD")' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ConvertToDateObject("2000-01-01", "YYYY-MM-DD")) + '</pre>';
returnString += '<p>NepaliFunctions.ConvertToDateObject("2000/01/01", "YYYY/MM/DD")' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ConvertToDateObject("2000/01/01", "YYYY/MM/DD")) + '</pre>';
returnString += '<p>NepaliFunctions.ConvertToDateObject("01-01-2000", "MM-DD-YYYY")' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ConvertToDateObject("01-01-2000", "MM-DD-YYYY")) + '</pre>';
returnString += '<p>NepaliFunctions.ConvertToDateObject("01/01/2000", "MM/DD/YYYY")' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ConvertToDateObject("01/01/2000", "MM/DD/YYYY")) + '</pre>';
returnString += '<p>NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "YYYY-MM-DD")' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "YYYY-MM-DD")) + '</pre>';
returnString += '<p>NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "YYYY/MM/DD")' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "YYYY/MM/DD")) + '</pre>';
returnString += '<p>NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "MM-DD-YYYY")' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "MM-DD-YYYY")) + '</pre>';
returnString += '<p>NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "MM/DD/YYYY")' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ConvertDateFormat({year: 2000, month: 1, day: 1}, "MM/DD/YYYY")) + '</pre>';
returnString += '<p>NepaliFunctions.AD2BS({year: 2001, month: 6, day: 1})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.AD2BS({year: 2001, month: 6, day: 1})) + '</pre>';
returnString += '<p>NepaliFunctions.AD2BS({year: 2008, month: 5, day: 28})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.AD2BS({year: 2008, month: 5, day: 28})) + '</pre>';
returnString += '<p>NepaliFunctions.BS2AD({year: 2058, month: 2, day: 19})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.BS2AD({year: 2058, month: 2, day: 19})) + '</pre>';
returnString += '<p>NepaliFunctions.BS2AD({year: 2065, month: 2, day: 15})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.BS2AD({year: 2065, month: 2, day: 15})) + '</pre>';
returnString += '<p>NepaliFunctions.ValidateBsDate({year: 2000, month: 2, day: 30})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ValidateBsDate({year: 2000, month: 2, day: 30})) + '</pre>';
returnString += '<p>NepaliFunctions.ValidateBsDate({year: 2064, month: 4, day: 32})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ValidateBsDate({year: 2064, month: 4, day: 32})) + '</pre>';
returnString += '<p>NepaliFunctions.ValidateBsDate({year: 2000, month: 13, day: 30})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ValidateBsDate({year: 2000, month: 13, day: 30})) + '</pre>';
returnString += '<p>NepaliFunctions.ValidateBsDate({year: 2000, month: 12, day: 32})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ValidateBsDate({year: 2000, month: 12, day: 32})) + '</pre>';
returnString += '<p>NepaliFunctions.GetCurrentAdDate()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetCurrentAdDate()) + '</pre>';
returnString += '<p>NepaliFunctions.GetCurrentAdYear()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetCurrentAdYear()) + '</pre>';
returnString += '<p>NepaliFunctions.GetCurrentAdMonth()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetCurrentAdMonth()) + '</pre>';
returnString += '<p>NepaliFunctions.GetCurrentAdDay()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetCurrentAdDay()) + '</pre>';
returnString += '<p>NepaliFunctions.GetCurrentBsDate()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetCurrentBsDate()) + '</pre>';
returnString += '<p>NepaliFunctions.GetCurrentBsYear()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetCurrentBsYear()) + '</pre>';
returnString += '<p>NepaliFunctions.GetCurrentBsMonth()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetCurrentBsMonth()) + '</pre>';
returnString += '<p>NepaliFunctions.GetCurrentBsDay()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetCurrentBsDay()) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdMonths()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdMonths()) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdMonth(0)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdMonth(0)) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdMonth(5)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdMonth(5)) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdMonth(11)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdMonth(11)) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdMonth(-1)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdMonth(-1)) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdMonth(12)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdMonth(12)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsMonths()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsMonths()) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsMonth(0)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsMonth(0)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsMonth(5)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsMonth(5)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsMonth(11)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsMonth(11)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsMonth(-1)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsMonth(-1)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsMonth(12)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsMonth(12)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsMonthsInUnicode()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsMonthsInUnicode()) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsMonthInUnicode(0)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsMonthInUnicode(0)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsMonthInUnicode(5)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsMonthInUnicode(5)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsMonthInUnicode(11)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsMonthInUnicode(11)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsMonthInUnicode(-1)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsMonthInUnicode(-1)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsMonthInUnicode(12)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsMonthInUnicode(12)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsDaysUnicode()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsDaysUnicode()) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsDayUnicode(0)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsDayUnicode(0)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsDayUnicode(4)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsDayUnicode(4)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsDayUnicode(7)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsDayUnicode(7)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsDaysUnicodeShort()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsDaysUnicodeShort()) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdDays()' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdDays()) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdDay(0)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdDay(0)) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdDay(5)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdDay(5)) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdDay(7)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdDay(7)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsFullDate({year: 2075, month: 3, day: 15}, false)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsFullDate({year: 2075, month: 3, day: 15}, false)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsFullDate({year: 2075, month: 5, day: 2}, false)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsFullDate({year: 2075, month: 5, day: 2}, false)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsFullDate({year: 2075, month: 3, day: 15}, true)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsFullDate({year: 2075, month: 3, day: 15}, true)) + '</pre>';
returnString += '<p>NepaliFunctions.GetBsFullDate({year: 2075, month: 5, day: 2}, true)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetBsFullDate({year: 2075, month: 5, day: 2}, true)) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdFullDate({year: 2001, month: 3, day: 15})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdFullDate({year: 2001, month: 3, day: 15})) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdFullDate({year: 2003, month: 5, day: 2})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdFullDate({year: 2003, month: 5, day: 2})) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdFullDay({year: 2001, month: 3, day: 15})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdFullDay({year: 2001, month: 3, day: 15})) + '</pre>';
returnString += '<p>NepaliFunctions.GetAdFullDay({year: 2003, month: 5, day: 2})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetAdFullDay({year: 2003, month: 5, day: 2})) + '</pre>';
returnString += '<p>NepaliFunctions.BsAddDays({year: 2001, month: 3, day: 15}, 2)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.BsAddDays({year: 2001, month: 3, day: 15}, 2)) + '</pre>';
returnString += '<p>NepaliFunctions.BsAddDays({year: 2003, month: 5, day: 2}, 90)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.BsAddDays({year: 2003, month: 5, day: 2}, 90)) + '</pre>';
returnString += '<p>NepaliFunctions.AdDatesDiff({year: 2001, month: 3, day: 15}, {year: 2001, month: 3, day: 17})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.AdDatesDiff({year: 2001, month: 3, day: 15}, {year: 2001, month: 3, day: 17})) + '</pre>';
returnString += '<p>NepaliFunctions.AdDatesDiff({year: 2003, month: 5, day: 2}, {year: 2003, month: 8, day: 1})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.AdDatesDiff({year: 2003, month: 5, day: 2}, {year: 2003, month: 8, day: 1})) + '</pre>';
returnString += '<p>NepaliFunctions.BsDatesDiff({year: 2001, month: 3, day: 15}, {year: 2001, month: 3, day: 17})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.BsDatesDiff({year: 2001, month: 3, day: 15}, {year: 2001, month: 3, day: 17})) + '</pre>';
returnString += '<p>NepaliFunctions.BsDatesDiff({year: 2003, month: 5, day: 2}, {year: 2003, month: 8, day: 1})' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.BsDatesDiff({year: 2003, month: 5, day: 2}, {year: 2003, month: 8, day: 1})) + '</pre>';
returnString += '<p>NepaliFunctions.GetDaysInAdMonth(2015, 2)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetDaysInAdMonth(2015, 2)) + '</pre>';
returnString += '<p>NepaliFunctions.GetDaysInAdMonth(2020, 1)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetDaysInAdMonth(2020, 1)) + '</pre>';
returnString += '<p>NepaliFunctions.GetDaysInBsMonth(2015, 2)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetDaysInBsMonth(2015, 2)) + '</pre>';
returnString += '<p>NepaliFunctions.GetDaysInBsMonth(2020, 1)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.GetDaysInBsMonth(2020, 1)) + '</pre>';
returnString += '<p>NepaliFunctions.ConvertToUnicode(123456789)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ConvertToUnicode(123456789)) + '</pre>';
returnString += '<p>NepaliFunctions.ConvertToUnicode(123.50)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ConvertToUnicode(123.50)) + '</pre>';
returnString += '<p>NepaliFunctions.ConvertToNumber("१२३४५६७८९")' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ConvertToNumber("१२३४५६७८९")) + '</pre>';
returnString += '<p>NepaliFunctions.ConvertToNumber("१२३.५")' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.ConvertToNumber("१२३.५")) + '</pre>';
returnString += '<p>NepaliFunctions.Get2DigitNo(1)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.Get2DigitNo(1)) + '</pre>';
returnString += '<p>NepaliFunctions.Get2DigitNo(12)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.Get2DigitNo(12)) + '</pre>';

returnString += '<p>NepaliFunctions.NumberToWords(123456000.12, true)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.NumberToWords(123456000.12, true)) + '</pre>';
returnString += '<p>NepaliFunctions.NumberToWords(12, true)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.NumberToWords(12, true)) + '</pre>';

returnString += '<p>NepaliFunctions.NumberToWords(123456000.12, false)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.NumberToWords(123456000.12, false)) + '</pre>';
returnString += '<p>NepaliFunctions.NumberToWords(12, false)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.NumberToWords(12, false)) + '</pre>';

returnString += '<p>NepaliFunctions.NumberToWordsUnicode(123456000.12, true)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.NumberToWordsUnicode(123456000.12, true)) + '</pre>';
returnString += '<p>NepaliFunctions.NumberToWordsUnicode(12, true)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.NumberToWordsUnicode(12, true)) + '</pre>';

returnString += '<p>NepaliFunctions.NumberToWordsUnicode(123456000.12, false)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.NumberToWordsUnicode(123456000.12, false)) + '</pre>';
returnString += '<p>NepaliFunctions.NumberToWordsUnicode(12, false)' + '</p>'
returnString += '<pre>' + JSON.stringify(NepaliFunctions.NumberToWordsUnicode(12, false)) + '</pre>';

document.getElementById('examples').innerHTML = returnString;